apiVersion: v1
kind: ServiceAccount
metadata:
  name: bench-sa
  namespace: bench
  annotations:
    kubernetes.io/service-account.name: bench-sa
automountServiceAccountToken: false
imagePullSecrets:
- name: ocir-secret
